'use strict';


/**
 *
 * rENTREE Integer  (optional)
 * rENTREE_lib Integer  (optional)
 * identifiant Paysage String  (optional)
 * eTABLISSEMENT String  (optional)
 * établissement String  (optional)
 * sigle String  (optional)
 * nombre d&#x27;étudiants inscrits (inscriptions principales) y compris doubles inscriptions CPGE Integer  (optional)
 * nombre d&#x27;étudiants inscrits (inscriptions principales) hors doubles inscriptions CPGE Integer  (optional)
 * nombre total d&#x27;étudiants inscrits (inscriptions principales et secondes) y compris doubles inscriptions CPGE Integer  (optional)
 * nombre total d&#x27;étudiants (inscriptions principales et secondes)  hors double inscription CPGE Integer  (optional)
 * nombre de nouveaux bacheliers inscrits y compris doubles inscriptions CPGE Integer  (optional)
 * nombre de nouveaux bacheliers inscrits hors double inscription CPGE Integer  (optional)
 * sexe  Femmes Integer  (optional)
 * sexe  Hommes Integer  (optional)
 * bac  Série L Integer  (optional)
 * bac  Série ES Integer  (optional)
 * bac  Série S Integer  (optional)
 * bac  Séries STMG Integer  (optional)
 * bac  Autres séries technologiques Integer  (optional)
 * bac  Baccalauréat professionnel Integer  (optional)
 * bac  Dispensés Integer  (optional)
 * âge au baccalauréat  En avance au bac d&#x27;un an ou plus Integer  (optional)
 * âge au baccalauréat  A l&#x27;heure Integer  (optional)
 * âge au baccalauréat  En retard au bac d&#x27;un an ou plus Integer  (optional)
 * âge au baccalauréat  Non renseigné ou non bachelier Integer  (optional)
 * attractivité départementale (département d&#x27;obtention du baccalauréat)  Même département Integer  (optional)
 * attractivité départementale (département d&#x27;obtention du baccalauréat)  Départements limitrophes Integer  (optional)
 * attractivité départementale (département d&#x27;obtention du baccalauréat)  Autres départements français Integer  (optional)
 * attractivité départementale (département d&#x27;obtention du baccalauréat)  Etranger Integer  (optional)
 * attractivité départementale (département d&#x27;obtention du baccalauréat)  Non renseigné Integer  (optional)
 * attractivité départementale (département d&#x27;obtention du baccalauréat)  Non bacheliers Integer  (optional)
 * etudiants en mobilité internationale Integer  (optional)
 * attractivité internationale  Etudiants de nationalité étrangère issus de système éducatif étranger Integer  (optional)
 * cycle universitaire (cursus LMD)  L (1er cycle) Integer  (optional)
 * cycle universitaire (cursus LMD)  M (2ème cycle) Integer  (optional)
 * cycle universitaire (cursus LMD)  D (3ème cycle) Integer  (optional)
 * type de diplôme  Diplômes nationaux Integer  (optional)
 * type de diplôme  Diplômes d&#x27;établissement Integer  (optional)
 * diplôme préparé  Diplôme d&#x27;accès aux études universitaires Integer  (optional)
 * diplôme préparé  Capacité en droit Integer  (optional)
 * diplôme préparé  Licence Integer  (optional)
 * diplôme préparé  Diplôme universitaire de technologie Integer  (optional)
 * diplôme préparé  CPGE universitaire Integer  (optional)
 * diplôme préparé  Licence professionnelle Integer  (optional)
 * diplôme préparé  Master enseignement Integer  (optional)
 * diplôme préparé  Autres masters Integer  (optional)
 * diplôme préparé  Formations d&#x27;ingénieurs Integer  (optional)
 * diplôme préparé  Formations d&#x27;IEP Integer  (optional)
 * diplôme préparé  PACES et PluriPASS Integer  (optional)
 * diplôme préparé  Formations paramédicales Integer  (optional)
 * diplôme préparé  Autres formations de santé Integer  (optional)
 * diplôme préparé  Doctorat Integer  (optional)
 * diplôme préparé  HDR Integer  (optional)
 * diplôme préparé  Diplômes d&#x27;établissement Integer  (optional)
 * diplôme préparé  Autres formations et diplômes Integer  (optional)
 * grande discipline  Droit, sciences économiques, AES Integer  (optional)
 * grande discipline  Lettres, langues et sciences humaines Integer  (optional)
 * grande discipline  Sciences et sciences de l&#x27;ingénieur Integer  (optional)
 * grande discipline  STAPS Integer  (optional)
 * grande discipline  Santé Integer  (optional)
 * grande discipline  Interdisciplinaire Integer  (optional)
 * discipline  Droit, sciences politiques Integer  (optional)
 * discipline  Sciences économiques, gestion Integer  (optional)
 * discipline  Administration économique et sociale Integer  (optional)
 * discipline  Pluridisciplinaire droit, sciences économiques, AES Integer  (optional)
 * discipline  Lettres, sciences du langage, arts Integer  (optional)
 * discipline  Langues Integer  (optional)
 * discipline  Sciences humaines et sociales Integer  (optional)
 * discipline  Pluridisciplinaire lettres, langues, sciences humaines Integer  (optional)
 * discipline  Sciences de la vie, de la terre et de l&#x27;univers Integer  (optional)
 * discipline  Sciences fondamentales et applications Integer  (optional)
 * discipline  Pluridisciplinaire sciences Integer  (optional)
 * discipline  STAPS Integer  (optional)
 * discipline  Médecine Integer  (optional)
 * discipline  Odontologie Integer  (optional)
 * discipline  Pharmacie Integer  (optional)
 * discipline  Pluridisciplinaire santé Integer  (optional)
 * discipline  Interdisciplinaire Integer  (optional)
 * secteur disciplinaire  Sciences juridiques Integer  (optional)
 * secteur disciplinaire  Sciences politiques Integer  (optional)
 * secteur disciplinaire  Pluridisciplinaire droit, sciences politiques Integer  (optional)
 * secteur disciplinaire  Sciences économiques Integer  (optional)
 * secteur disciplinaire  Sciences de gestion Integer  (optional)
 * secteur disciplinaire  Pluridisciplinaire sciences économiques et gestion Integer  (optional)
 * secteur disciplinaire  Administration économique et sociale Integer  (optional)
 * secteur disciplinaire  Pluridisciplinaire droit, sciences économiques, AES Integer  (optional)
 * secteur disciplinaire  Sciences du langage, linguistique Integer  (optional)
 * secteur disciplinaire  Langues et littératures anciennes Integer  (optional)
 * secteur disciplinaire  Langues et littératures françaises Integer  (optional)
 * secteur disciplinaire  Littérature générale et comparée Integer  (optional)
 * secteur disciplinaire  Arts Integer  (optional)
 * secteur disciplinaire  Pluridisciplinaire lettres, sciences du langage, arts Integer  (optional)
 * secteur disciplinaire  Français, langue étrangère Integer  (optional)
 * secteur disciplinaire  Langues et littératures étrangères Integer  (optional)
 * secteur disciplinaire  Langues étrangères appliquées Integer  (optional)
 * secteur disciplinaire  Cultures et langues régionales Integer  (optional)
 * secteur disciplinaire  Pluridisciplinaire langues Integer  (optional)
 * secteur disciplinaire  Philosophie, épistémologie Integer  (optional)
 * secteur disciplinaire  Histoire Integer  (optional)
 * secteur disciplinaire  Géographie Integer  (optional)
 * secteur disciplinaire  Aménagement Integer  (optional)
 * secteur disciplinaire  Archéologie, ethnologie, préhistoire Integer  (optional)
 * secteur disciplinaire  Sciences religieuses Integer  (optional)
 * secteur disciplinaire  Psychologie Integer  (optional)
 * secteur disciplinaire  Sociologie, démographie Integer  (optional)
 * secteur disciplinaire  Sciences de l&#x27;éducation Integer  (optional)
 * secteur disciplinaire  Sciences de l&#x27;information et la communication Integer  (optional)
 * secteur disciplinaire  Pluridisciplinaire sciences humaines et sociales Integer  (optional)
 * secteur disciplinaire  Pluridisciplinaire lettres, langues, sciences humaines Integer  (optional)
 * secteur disciplinaire  Sciences de l&#x27;univers Integer  (optional)
 * secteur disciplinaire  Sciences de la vie Integer  (optional)
 * secteur disciplinaire  Pluridisciplinaire sciences de la vie, de la santé, de la terre et de l&#x27;univers Integer  (optional)
 * secteur disciplinaire  Mathématiques Integer  (optional)
 * secteur disciplinaire  Physique Integer  (optional)
 * secteur disciplinaire  Chimie Integer  (optional)
 * secteur disciplinaire  Mathématiques appliquées et sciences sociales Integer  (optional)
 * secteur disciplinaire  Mécanique, génie mécanique Integer  (optional)
 * secteur disciplinaire  Génie civil Integer  (optional)
 * secteur disciplinaire  Génie des procédés Integer  (optional)
 * secteur disciplinaire  Informatique Integer  (optional)
 * secteur disciplinaire  Électronique, génie électrique Integer  (optional)
 * secteur disciplinaire  Technologie et sciences industrielles Integer  (optional)
 * secteur disciplinaire  Formation générale aux métiers de l&#x27;ingénieur Integer  (optional)
 * secteur disciplinaire  Mathématique et informatique Integer  (optional)
 * secteur disciplinaire  Physique et chimie Integer  (optional)
 * secteur disciplinaire  Pluridisciplinaire sciences fondamentales et applications Integer  (optional)
 * secteur disciplinaire  Pluridisciplinaire sciences Integer  (optional)
 * secteur disciplinaire  STAPS Integer  (optional)
 * secteur disciplinaire  Médecine Integer  (optional)
 * secteur disciplinaire  Odontologie Integer  (optional)
 * secteur disciplinaire  Pharmacie Integer  (optional)
 * secteur disciplinaire  Pluridisciplinaire santé Integer  (optional)
 * secteur disciplinaire  Interdisciplinaire Integer  (optional)
 * type d&#x27;établissement String  (optional)
 * eTABLISSEMENT_TYPE String  (optional)
 * typologie d&#x27;établissement String  (optional)
 * élément wikidata String  (optional)
 * identifiant ETER String  (optional)
 * identifiant ROR String  (optional)
 * champ statistique (universités et établissements assimilés France métro+DOM) String  (optional)
 * localisation du siège de l’établissement String  (optional)
 * rEG_ETAB String  (optional)
 * région du siège de l’établissement String  (optional)
 * aCA_ETAB String  (optional)
 * académie du siège de l’établissement String  (optional)
 * dEP_ETAB String  (optional)
 * département du siège de l’établissement String  (optional)
 * uUCR_ETAB String  (optional)
 * unité urbaine ou commune rurale du siège de l’établissement String  (optional)
 * cOM_ETAB Integer  (optional)
 * commune du siège de l’établissement String  (optional)
 * returns Object
 **/
exports.exploreDatasetFr_esr_statistiques_sur_les_effectifs_d_etudiants_inscrits_par_etablissementTableGET = function(rENTREE,rENTREE_lib,identifiant Paysage,eTABLISSEMENT,établissement,sigle,nombre d&#x27;étudiants inscrits (inscriptions principales) y compris doubles inscriptions CPGE,nombre d&#x27;étudiants inscrits (inscriptions principales) hors doubles inscriptions CPGE,nombre total d&#x27;étudiants inscrits (inscriptions principales et secondes) y compris doubles inscriptions CPGE,nombre total d&#x27;étudiants (inscriptions principales et secondes)  hors double inscription CPGE,nombre de nouveaux bacheliers inscrits y compris doubles inscriptions CPGE,nombre de nouveaux bacheliers inscrits hors double inscription CPGE,sexe  Femmes,sexe  Hommes,bac  Série L,bac  Série ES,bac  Série S,bac  Séries STMG,bac  Autres séries technologiques,bac  Baccalauréat professionnel,bac  Dispensés,âge au baccalauréat  En avance au bac d&#x27;un an ou plus,âge au baccalauréat  A l&#x27;heure,âge au baccalauréat  En retard au bac d&#x27;un an ou plus,âge au baccalauréat  Non renseigné ou non bachelier,attractivité départementale (département d&#x27;obtention du baccalauréat)  Même département,attractivité départementale (département d&#x27;obtention du baccalauréat)  Départements limitrophes,attractivité départementale (département d&#x27;obtention du baccalauréat)  Autres départements français,attractivité départementale (département d&#x27;obtention du baccalauréat)  Etranger,attractivité départementale (département d&#x27;obtention du baccalauréat)  Non renseigné,attractivité départementale (département d&#x27;obtention du baccalauréat)  Non bacheliers,etudiants en mobilité internationale,attractivité internationale  Etudiants de nationalité étrangère issus de système éducatif étranger,cycle universitaire (cursus LMD)  L (1er cycle),cycle universitaire (cursus LMD)  M (2ème cycle),cycle universitaire (cursus LMD)  D (3ème cycle),type de diplôme  Diplômes nationaux,type de diplôme  Diplômes d&#x27;établissement,diplôme préparé  Diplôme d&#x27;accès aux études universitaires,diplôme préparé  Capacité en droit,diplôme préparé  Licence,diplôme préparé  Diplôme universitaire de technologie,diplôme préparé  CPGE universitaire,diplôme préparé  Licence professionnelle,diplôme préparé  Master enseignement,diplôme préparé  Autres masters,diplôme préparé  Formations d&#x27;ingénieurs,diplôme préparé  Formations d&#x27;IEP,diplôme préparé  PACES et PluriPASS,diplôme préparé  Formations paramédicales,diplôme préparé  Autres formations de santé,diplôme préparé  Doctorat,diplôme préparé  HDR,diplôme préparé  Diplômes d&#x27;établissement,diplôme préparé  Autres formations et diplômes,grande discipline  Droit, sciences économiques, AES,grande discipline  Lettres, langues et sciences humaines,grande discipline  Sciences et sciences de l&#x27;ingénieur,grande discipline  STAPS,grande discipline  Santé,grande discipline  Interdisciplinaire,discipline  Droit, sciences politiques,discipline  Sciences économiques, gestion,discipline  Administration économique et sociale,discipline  Pluridisciplinaire droit, sciences économiques, AES,discipline  Lettres, sciences du langage, arts,discipline  Langues,discipline  Sciences humaines et sociales,discipline  Pluridisciplinaire lettres, langues, sciences humaines,discipline  Sciences de la vie, de la terre et de l&#x27;univers,discipline  Sciences fondamentales et applications,discipline  Pluridisciplinaire sciences,discipline  STAPS,discipline  Médecine,discipline  Odontologie,discipline  Pharmacie,discipline  Pluridisciplinaire santé,discipline  Interdisciplinaire,secteur disciplinaire  Sciences juridiques,secteur disciplinaire  Sciences politiques,secteur disciplinaire  Pluridisciplinaire droit, sciences politiques,secteur disciplinaire  Sciences économiques,secteur disciplinaire  Sciences de gestion,secteur disciplinaire  Pluridisciplinaire sciences économiques et gestion,secteur disciplinaire  Administration économique et sociale,secteur disciplinaire  Pluridisciplinaire droit, sciences économiques, AES,secteur disciplinaire  Sciences du langage, linguistique,secteur disciplinaire  Langues et littératures anciennes,secteur disciplinaire  Langues et littératures françaises,secteur disciplinaire  Littérature générale et comparée,secteur disciplinaire  Arts,secteur disciplinaire  Pluridisciplinaire lettres, sciences du langage, arts,secteur disciplinaire  Français, langue étrangère,secteur disciplinaire  Langues et littératures étrangères,secteur disciplinaire  Langues étrangères appliquées,secteur disciplinaire  Cultures et langues régionales,secteur disciplinaire  Pluridisciplinaire langues,secteur disciplinaire  Philosophie, épistémologie,secteur disciplinaire  Histoire,secteur disciplinaire  Géographie,secteur disciplinaire  Aménagement,secteur disciplinaire  Archéologie, ethnologie, préhistoire,secteur disciplinaire  Sciences religieuses,secteur disciplinaire  Psychologie,secteur disciplinaire  Sociologie, démographie,secteur disciplinaire  Sciences de l&#x27;éducation,secteur disciplinaire  Sciences de l&#x27;information et la communication,secteur disciplinaire  Pluridisciplinaire sciences humaines et sociales,secteur disciplinaire  Pluridisciplinaire lettres, langues, sciences humaines,secteur disciplinaire  Sciences de l&#x27;univers,secteur disciplinaire  Sciences de la vie,secteur disciplinaire  Pluridisciplinaire sciences de la vie, de la santé, de la terre et de l&#x27;univers,secteur disciplinaire  Mathématiques,secteur disciplinaire  Physique,secteur disciplinaire  Chimie,secteur disciplinaire  Mathématiques appliquées et sciences sociales,secteur disciplinaire  Mécanique, génie mécanique,secteur disciplinaire  Génie civil,secteur disciplinaire  Génie des procédés,secteur disciplinaire  Informatique,secteur disciplinaire  Électronique, génie électrique,secteur disciplinaire  Technologie et sciences industrielles,secteur disciplinaire  Formation générale aux métiers de l&#x27;ingénieur,secteur disciplinaire  Mathématique et informatique,secteur disciplinaire  Physique et chimie,secteur disciplinaire  Pluridisciplinaire sciences fondamentales et applications,secteur disciplinaire  Pluridisciplinaire sciences,secteur disciplinaire  STAPS,secteur disciplinaire  Médecine,secteur disciplinaire  Odontologie,secteur disciplinaire  Pharmacie,secteur disciplinaire  Pluridisciplinaire santé,secteur disciplinaire  Interdisciplinaire,type d&#x27;établissement,eTABLISSEMENT_TYPE,typologie d&#x27;établissement,élément wikidata,identifiant ETER,identifiant ROR,champ statistique (universités et établissements assimilés France métro+DOM),localisation du siège de l’établissement,rEG_ETAB,région du siège de l’établissement,aCA_ETAB,académie du siège de l’établissement,dEP_ETAB,département du siège de l’établissement,uUCR_ETAB,unité urbaine ou commune rurale du siège de l’établissement,cOM_ETAB,commune du siège de l’établissement) {
  return new Promise(function(resolve, reject) {
    var examples = {};
    examples['application/json'] = { };
    if (Object.keys(examples).length > 0) {
      resolve(examples[Object.keys(examples)[0]]);
    } else {
      resolve();
    }
  });
}

