'use strict';


/**
 *
 * session Integer  (optional)
 * statut de l’établissement de la filière de formation (public, privé…) String  (optional)
 * code UAI de l&#x27;établissement String  (optional)
 * établissement String  (optional)
 * code départemental de l’établissement Integer  (optional)
 * département de l’établissement String  (optional)
 * région de l’établissement String  (optional)
 * académie de l’établissement String  (optional)
 * filière de formation très agrégée String  (optional)
 * filière de formation String  (optional)
 * concours communs et banques d&#x27;épreuves String  (optional)
 * filière de formation détaillée String  (optional)
 * filière de formation très détaillée String  (optional)
 * lien de la formation sur la plateforme Parcoursup String  (optional)
 * coordonnées GPS de la formation BigDecimal  (optional)
 * capacité de l’établissement par formation Integer  (optional)
 * effectif total des candidats pour une formation Integer  (optional)
 * dont effectif des candidates pour une formation Integer  (optional)
 * effectif total des candidats en phase principale Integer  (optional)
 * dont effectif des candidats ayant postulé en internat Integer  (optional)
 * effectif des candidats néo bacheliers généraux en phase principale Integer  (optional)
 * dont effectif des candidats boursiers néo bacheliers généraux en phase principale Integer  (optional)
 * effectif des candidats néo bacheliers technologiques en phase principale Integer  (optional)
 * dont effectif des candidats boursiers néo bacheliers technologiques en phase principale Integer  (optional)
 * effectif des candidats néo bacheliers professionnels en phase principale Integer  (optional)
 * dont effectif des candidats boursiers néo bacheliers professionnels en phase principale Integer  (optional)
 * effectif des autres candidats en phase principale Integer  (optional)
 * effectif total des candidats en phase complémentaire Integer  (optional)
 * effectif des candidats néo bacheliers généraux en phase complémentaire Integer  (optional)
 * effectif des candidats néo bacheliers technologique en phase complémentaire Integer  (optional)
 * effectif des candidats néo bacheliers professionnels en phase complémentaire Integer  (optional)
 * effectifs des autres candidats en phase complémentaire Integer  (optional)
 * effectif total des candidats classés par l’établissement en phase principale Integer  (optional)
 * effectif des candidats classés par l’établissement en phase complémentaire Integer  (optional)
 * effectif des candidats classés par l’établissement en internat (CPGE) Integer  (optional)
 * effectif des candidats classés par l’établissement hors internat (CPGE) Integer  (optional)
 * effectif des candidats néo bacheliers généraux classés par l’établissement Integer  (optional)
 * dont effectif des candidats boursiers néo bacheliers généraux classés par l’établissement Integer  (optional)
 * effectif des candidats néo bacheliers technologiques classés par l’établissement Integer  (optional)
 * dont effectif des candidats boursiers néo bacheliers technologiques classés par l’établissement Integer  (optional)
 * effectif des candidats néo bacheliers professionnels classés par l’établissement Integer  (optional)
 * dont effectif des candidats boursiers néo bacheliers professionnels classés par l’établissement Integer  (optional)
 * effectif des autres candidats classés par l’établissement Integer  (optional)
 * effectif total des candidats ayant reçu une proposition d’admission de la part de l’établissement Integer  (optional)
 * rang du dernier appelé Integer  (optional)
 * effectif total des candidats ayant accepté la proposition de l’établissement (admis) Integer  (optional)
 * dont effectif des candidates admises Integer  (optional)
 * effectif des admis en phase principale Integer  (optional)
 * effectif des admis en phase complémentaire Integer  (optional)
 * dont effectif des admis ayant reçu leur proposition d’admission à l&#x27;ouverture de la procédure principale Integer  (optional)
 * dont effectif des admis ayant reçu leur proposition d’admission avant le baccalauréat Integer  (optional)
 * dont effectif des admis ayant reçu leur proposition d’admission avant la fin de la procédure principale Integer  (optional)
 * dont effectif des admis en internat Integer  (optional)
 * dont effectif des admis boursiers néo bacheliers Integer  (optional)
 * effectif des admis néo bacheliers Integer  (optional)
 * effectif des admis néo bacheliers généraux Integer  (optional)
 * effectif des admis néo bacheliers technologiques Integer  (optional)
 * effectif des admis néo bacheliers professionnels Integer  (optional)
 * effectif des autres candidats admis Integer  (optional)
 * dont effectif des admis néo bacheliers sans information sur la mention au bac Integer  (optional)
 * dont effectif des admis néo bacheliers sans mention au bac Integer  (optional)
 * dont effectif des admis néo bacheliers avec mention Assez Bien au bac Integer  (optional)
 * dont effectif des admis néo bacheliers avec mention Bien au bac Integer  (optional)
 * dont effectif des admis néo bacheliers avec mention Très Bien au bac Integer  (optional)
 * effectif des admis néo bacheliers généraux ayant eu une mention au bac Integer  (optional)
 * effectif des admis néo bacheliers technologiques ayant eu une mention au bac Integer  (optional)
 * effectif des admis néo bacheliers professionnels ayant eu une mention au bac Integer  (optional)
 * dont effectif des admis issus du même établissement (BTS/CPGE) Integer  (optional)
 * dont effectif des admises issues du même établissement (BTS/CPGE) Integer  (optional)
 * dont effectif des admis issus de la même académie Integer  (optional)
 * dont effectif des admis issus de la même académie (Paris/Créteil/Versailles réunies) Integer  (optional)
 * % d’admis ayant reçu leur proposition d’admission à l&#x27;ouverture de la procédure principale BigDecimal  (optional)
 * % d’admis ayant reçu leur proposition d’admission avant le baccalauréat BigDecimal  (optional)
 * % d’admis ayant reçu leur proposition d’admission avant la fin de la procédure principale BigDecimal  (optional)
 * % d’admis dont filles BigDecimal  (optional)
 * % d’admis néo bacheliers issus de la même académie BigDecimal  (optional)
 * % d’admis néo bacheliers issus de la même académie (Paris/Créteil/Versailles réunies) Integer  (optional)
 * % d’admis néo bacheliers issus du même établissement (BTS/CPGE) Integer  (optional)
 * % d’admis néo bacheliers boursiers BigDecimal  (optional)
 * % d’admis néo bacheliers BigDecimal  (optional)
 * % d’admis néo bacheliers sans information sur la mention au bac BigDecimal  (optional)
 * % d’admis néo bacheliers sans mention au bac BigDecimal  (optional)
 * % d’admis néo bacheliers avec mention Assez Bien au bac BigDecimal  (optional)
 * % d’admis néo bacheliers avec mention Bien au bac BigDecimal  (optional)
 * % d’admis néo bacheliers avec mention Très Bien au bac BigDecimal  (optional)
 * % d’admis néo bacheliers généraux BigDecimal  (optional)
 * dont % d’admis avec mention BigDecimal  (optional)
 * % d’admis néo bacheliers technologiques BigDecimal  (optional)
 * dont % d’admis avec mention.1 BigDecimal  (optional)
 * % d’admis néo bacheliers professionnels BigDecimal  (optional)
 * dont % d’admis avec mention.2 BigDecimal  (optional)
 * tri String  (optional)
 * returns Object
 **/
exports.exploreDatasetFr_esr_parcoursupTable_GET = function(session,statut de l’établissement de la filière de formation (public, privé…),code UAI de l&#x27;établissement,établissement,code départemental de l’établissement,département de l’établissement,région de l’établissement,académie de l’établissement,filière de formation très agrégée,filière de formation,concours communs et banques d&#x27;épreuves,filière de formation détaillée,filière de formation très détaillée,lien de la formation sur la plateforme Parcoursup,coordonnées GPS de la formation,capacité de l’établissement par formation,effectif total des candidats pour une formation,dont effectif des candidates pour une formation,effectif total des candidats en phase principale,dont effectif des candidats ayant postulé en internat,effectif des candidats néo bacheliers généraux en phase principale,dont effectif des candidats boursiers néo bacheliers généraux en phase principale,effectif des candidats néo bacheliers technologiques en phase principale,dont effectif des candidats boursiers néo bacheliers technologiques en phase principale,effectif des candidats néo bacheliers professionnels en phase principale,dont effectif des candidats boursiers néo bacheliers professionnels en phase principale,effectif des autres candidats en phase principale,effectif total des candidats en phase complémentaire,effectif des candidats néo bacheliers généraux en phase complémentaire,effectif des candidats néo bacheliers technologique en phase complémentaire,effectif des candidats néo bacheliers professionnels en phase complémentaire,effectifs des autres candidats en phase complémentaire,effectif total des candidats classés par l’établissement en phase principale,effectif des candidats classés par l’établissement en phase complémentaire,effectif des candidats classés par l’établissement en internat (CPGE),effectif des candidats classés par l’établissement hors internat (CPGE),effectif des candidats néo bacheliers généraux classés par l’établissement,dont effectif des candidats boursiers néo bacheliers généraux classés par l’établissement,effectif des candidats néo bacheliers technologiques classés par l’établissement,dont effectif des candidats boursiers néo bacheliers technologiques classés par l’établissement,effectif des candidats néo bacheliers professionnels classés par l’établissement,dont effectif des candidats boursiers néo bacheliers professionnels classés par l’établissement,effectif des autres candidats classés par l’établissement,effectif total des candidats ayant reçu une proposition d’admission de la part de l’établissement,rang du dernier appelé,effectif total des candidats ayant accepté la proposition de l’établissement (admis),dont effectif des candidates admises,effectif des admis en phase principale,effectif des admis en phase complémentaire,dont effectif des admis ayant reçu leur proposition d’admission à l&#x27;ouverture de la procédure principale,dont effectif des admis ayant reçu leur proposition d’admission avant le baccalauréat,dont effectif des admis ayant reçu leur proposition d’admission avant la fin de la procédure principale,dont effectif des admis en internat,dont effectif des admis boursiers néo bacheliers,effectif des admis néo bacheliers,effectif des admis néo bacheliers généraux,effectif des admis néo bacheliers technologiques,effectif des admis néo bacheliers professionnels,effectif des autres candidats admis,dont effectif des admis néo bacheliers sans information sur la mention au bac,dont effectif des admis néo bacheliers sans mention au bac,dont effectif des admis néo bacheliers avec mention Assez Bien au bac,dont effectif des admis néo bacheliers avec mention Bien au bac,dont effectif des admis néo bacheliers avec mention Très Bien au bac,effectif des admis néo bacheliers généraux ayant eu une mention au bac,effectif des admis néo bacheliers technologiques ayant eu une mention au bac,effectif des admis néo bacheliers professionnels ayant eu une mention au bac,dont effectif des admis issus du même établissement (BTS/CPGE),dont effectif des admises issues du même établissement (BTS/CPGE),dont effectif des admis issus de la même académie,dont effectif des admis issus de la même académie (Paris/Créteil/Versailles réunies),% d’admis ayant reçu leur proposition d’admission à l&#x27;ouverture de la procédure principale,% d’admis ayant reçu leur proposition d’admission avant le baccalauréat,% d’admis ayant reçu leur proposition d’admission avant la fin de la procédure principale,% d’admis dont filles,% d’admis néo bacheliers issus de la même académie,% d’admis néo bacheliers issus de la même académie (Paris/Créteil/Versailles réunies),% d’admis néo bacheliers issus du même établissement (BTS/CPGE),% d’admis néo bacheliers boursiers,% d’admis néo bacheliers,% d’admis néo bacheliers sans information sur la mention au bac,% d’admis néo bacheliers sans mention au bac,% d’admis néo bacheliers avec mention Assez Bien au bac,% d’admis néo bacheliers avec mention Bien au bac,% d’admis néo bacheliers avec mention Très Bien au bac,% d’admis néo bacheliers généraux,dont % d’admis avec mention,% d’admis néo bacheliers technologiques,dont % d’admis avec mention.1,% d’admis néo bacheliers professionnels,dont % d’admis avec mention.2,tri) {
  return new Promise(function(resolve, reject) {
    var examples = {};
    examples['application/json'] = { };
    if (Object.keys(examples).length > 0) {
      resolve(examples[Object.keys(examples)[0]]);
    } else {
      resolve();
    }
  });
}

